apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: boiling-ocelot-python 
  janus-idp.io/tekton: boiling-ocelot-python
  backstage.io/kubernetes-id: boiling-ocelot-python
  backstage.io/kubernetes-namespace: rhtap-dmo 
  app.kubernetes.io/part-of: boiling-ocelot-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  